version: '2'

networks:
  app-tier:
    driver: bridge

services:
  kafka:
    image: 'bitnami/kafka:latest'
    networks:
      - app-tier
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - ALLOW_ANONYMOUS_LOGIN=yes
#  my-app:
#    build:
#      context: ./
#    networks:
#      - app-tier
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes


  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    restart: "no"
    networks:
      - app-tier
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"
    depends_on:
      - "kafka"

#version: "3.9"
#services:
#  kafka:
#    image: bitnami/kafka:latest
#    ports:
#      - "9092:9092"
#      - "29092:29092"
#    environment:
#        KAFKA_BROKER_ID: 1
#        KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
#        ALLOW_PLAINTEXT_LISTENER: "yes"
#        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
#        KAFKA_LISTENERS: PLAINTEXT://:9092,PLAINTEXT_HOST://0.0.0.0:29092
#        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
#    image: bitnami/kafka:latest
#    ports:
#      - "9092:9092"
#    environment:
#     - ALLOW_PLAINTEXT_LISTENER=yes
#     - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
#     - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
#     - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
#
#
#  zookeeper:
#    image: bitnami/kafka:latest
#    ports:
#      - "2181:2181"
#    environment:
#      ALLOW_ANONYMOUS_LOGIN: "yes"
#
#  my-app:
#    build:
#      context: ./


#______________________
#version: '3.1'
#services:
#  zookeepeer:
#    image: bitnami/kafka:latest
#    ports:
#      - '2181:2181'
#  kafka:
#    image: wurstmeister/kafka
#    ports:
#      - '9092:9092'
#    environment:
#      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
#      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
#      KAFKA_CREATE_TOPICS: "topic1:1:3"
#      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
#      KAFKA_CFG_ADVERTISED_LISTENERS: =PLAINTEXT://localhost:9092
#      ALLOW_PLAINTEXT_LISTENER: "yes"


#  java:
#    image: openjdk:17
#    restart: always
#  zookeeper:
#    image: 'bitnami/zookeeper:latest'
#    ports:
#      - '2181:2181'
#    environment:
#      - ALLOW_ANONYMOUS_LOGIN=yes
#  kafka:
#    image: 'bitnami/kafka:latest'
#    ports:
#      - '9092:9092'
#    environment:
#      - KAFKA_BROKER_ID=1
#      - KAFKA_LISTENERS=localhost://:9092
#      - KAFKA_ADVERTISED_LISTENERS=localhost://127.0.0.1:9092
#      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
#      - ALLOW_PLAINTEXT_LISTENER=yes
#    depends_on:
#      - zookeeper